version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: "8000"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      PGDATABASE: "postgres"
      PGHOST: "db"
      PGPORT: "5432"
      JWT_SECRET: "181dda110a0b796cd2a1f7a9baed1534d8a460087867940faf5d5bf9aa152174"
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo_pgdb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/password.txt
